name: Truffle Hog Scan

on: [push]

jobs:
  truffle-hog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # - name: Run Truffle Hog
      #   run: | 
      #     pip install trufflehog
      #     trufflehog --regex https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/DigitalInnovation/PrScanBot-Test.git          
      #   env:
      #     GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: TruffleHog Bot scan
        continue-on-error: true
      #   uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
      #   with:
      #       args: --fail-verified ${{ github.event.repository.default_branch }} HEAD --json 

        run: |
            echo "----------Download Latest TruffleHog Binaries-----------"
            curl -q "https://storage.googleapis.com/thog-releases/trufflehog-scanner/latest/fetch.sh" | bash
            echo "----------Binary Scanning-----------"
            ./trufflehog --fail-verified git ${{ github.event.repository.default_branch }} HEAD --json > trufflehog-findings.json

      - name: truffle json view
        continue-on-error: true
        run:  cat trufflehog-findings.json

      - name: Convert JSON to SARIF
        continue-on-error: true
        run: |
          # Use jq to convert JSON to SARIF
          jq -n '. | {version: "2.1.0", runs: [input]}' --slurpfile input trufflehog-findings.json > trufflehog-findings.sarif
        working-directory: ${{ github.workspace }}
        
      - name: Upload SARIF to GitHub Security
        continue-on-error: true  
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trufflehog-findings.sarif
